function camera = setup_camera(egoVehicle)

    camera = visionDetectionGenerator(...
        'SensorIndex',          1,        ...
        'SensorLocation',       [3.4, 0], ...
        'Height',               1.5,      ...
        'Pitch',                1,        ...
        'MaxRange',             50,       ...
        'DetectionProbability', 0.95);

    fprintf('   -> Camera sensor configured: MaxRange=50m, DetProb=95%%\n');

end
